sudo: required
services:
    - docker

language: generic

before_install:
    - docker build -t rizkyian78/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rizkyian78/docker-react npm run test