sudo: required
services:
    - docker

language: generic

before_install:
    - docker build -t rizkyian78/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true rizkyian78/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "es-west-2"
    app: "docker_react"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-es-west-2-32131241"
    bucket_path: "docker_react"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"